# frozen_string_literal: true

module Jekyll
  # Resolves _data/photos_best.yml — the hand-curated edit — into the ordered,
  # display-ready list the /photos/ selects view renders (site.data.photos_selects).
  #
  # The edit lives in a data file rather than in each photo's frontmatter
  # because _photos/*.md is generated by photo_exif_generator.rb, which
  # rewrites that frontmatter and would drop a hand-added field — and because
  # a curated edit is an *order*, not a sort, which a YAML list carries for
  # free. Entries name a file in assets/photos/; everything else about the
  # photo (date, geocoded location) is read off the generated collection
  # document, so the edit only carries what curation actually adds: the
  # sequence, and any override for a title or place the generator got wrong.
  #
  # Distils each entry down to plain strings the way places.rb distils venues,
  # so the layout stays dumb. An entry naming a file that isn't there is
  # skipped with a warning rather than breaking the build.
  class PhotosBestGenerator < Generator
    safe true
    # After photo_exif_generator (:low) has had its pass at the collection.
    priority :lowest

    PHOTOS_PREFIX = '/assets/photos/'
    # Countries the caption drops, matching what photo-stream.js hides in the
    # stream's pill: at home the country is noise, abroad it's the point.
    IMPLIED_COUNTRIES = ['united states', 'usa', 'us'].freeze

    def generate(site)
      site.data['photos_selects'] = []

      entries = site.data['photos_best']
      unless entries.is_a?(Array) && !entries.empty?
        Jekyll.logger.warn 'PhotosBest:', '_data/photos_best.yml is missing or empty — /photos/ will render its empty state.'
        return
      end

      by_image = index_photos(site)

      site.data['photos_selects'] = entries.filter_map do |entry|
        next unless entry.is_a?(Hash)

        file = entry['file'].to_s.strip
        if file.empty?
          Jekyll.logger.warn 'PhotosBest:', 'skipping an entry in _data/photos_best.yml with no `file:`.'
          next
        end

        photo = by_image["#{PHOTOS_PREFIX}#{file}"]
        if photo.nil?
          Jekyll.logger.warn 'PhotosBest:', "no photo found for #{file.inspect} — check the filename against assets/photos/."
          next
        end

        build_select(entry, photo)
      end
    end

    private

    def index_photos(site)
      docs = site.collections['photos']&.docs || []
      docs.each_with_object({}) do |doc, index|
        image = doc.data['image']
        index[image.to_s.strip] = doc if image
      end
    end

    def build_select(entry, photo)
      # Only a hand-written title is worth showing: the generator's is the
      # filename in title case ("Favorites 2 Of 3"), which is noise as a
      # caption and worse as alt text.
      title = presence(entry['title'])
      place = presence(entry['place']) || format_place(photo.data['location'])
      year = presence(entry['year'])&.to_s || year_of(photo.data['date'])

      {
        'image' => photo.data['image'],
        'url' => photo.url,
        'title' => title,
        'place' => place,
        'year' => year,
        'alt' => title || [place, year].compact.join(', ').then { |s| s.empty? ? 'Photograph' : s }
      }
    end

    # "Chilmark, United States" → "Chilmark"; "Milano, Italia" → "Milano, Italia".
    def format_place(location)
      location = presence(location)
      return nil unless location

      city, *rest = location.split(',').map(&:strip)
      return location if rest.empty?

      country = rest.join(', ')
      IMPLIED_COUNTRIES.include?(country.downcase) ? city : "#{city}, #{country}"
    end

    def year_of(date)
      return nil unless date

      date.respond_to?(:year) ? date.year.to_s : date.to_s[0, 4]
    end

    def presence(value)
      string = value.to_s.strip
      string.empty? ? nil : string
    end
  end
end
