# frozen_string_literal: true

require "net/http"
require "uri"
require "json"
require "yaml"

# Country lookup by coordinates, for Places destinations nothing else can place.
#
# _data/places_geo.yml is curated by hand and the vault can name a country
# itself (see places.rb), but a brand-new city that mentions no country
# anywhere would otherwise fall into the "Elsewhere" bucket until someone
# noticed the build warning. Every venue already carries `location`
# coordinates, so the answer is sitting right there — this asks OpenStreetMap's
# Nominatim what country those coordinates are in.
#
# The result is cached in _places_geo_cache.yml, keyed by city, in the same
# "City: Country" shape as places_geo.yml's `countries:` block — so a generated
# line can be promoted to a curated one by moving it between files. Commit the
# cache and the lookup never runs again for that city; the steady state is zero
# network calls per build.
#
# It deliberately does *not* live in _data/, even though that's where it would
# read most naturally next to places_geo.yml. Jekyll parses everything in
# _data/ itself, before any plugin runs, and aborts the build on a YAML syntax
# error — so a half-written or hand-mangled cache would take the whole site
# down, and the rescue in load_cache below would never get a chance to ignore
# it. A leading underscore keeps Jekyll from reading *or* publishing the file,
# leaving it plugin state that can only ever degrade into an extra lookup.
#
# Guardrails, because this runs inside a deploy:
#
#   * One lookup per unknown *city*, not per venue, and never for a city the
#     cache or the curated data already answers.
#   * MAX_LOOKUPS per build, so importing a hundred new places can't turn into
#     a hundred sequential requests.
#   * A circuit breaker: after MAX_FAILURES consecutive failures it stops
#     trying for the rest of the build. Without it, a blocked or down endpoint
#     would cost a timeout apiece and could add minutes to a deploy.
#   * Short timeouts, one request per second (Nominatim's usage policy), and a
#     User-Agent identifying the site (also their policy).
#   * Every failure is soft: the city falls back to "Elsewhere" exactly as it
#     did before, and the build carries on.
#
# Set PLACES_GEOCODE=0 to switch the whole thing off; PLACES_GEOCODE_ENDPOINT
# points it at a different Nominatim (a self-hosted one, or a stub in tests).
class PlacesGeocoder
  CACHE_PATH = "_places_geo_cache.yml"
  DEFAULT_ENDPOINT = "https://nominatim.openstreetmap.org/reverse"
  USER_AGENT = "coopersmith.nyc Jekyll build (+https://coopersmith.nyc)"
  MAX_LOOKUPS = 25
  MAX_FAILURES = 2
  THROTTLE = 1.0
  TIMEOUT = 5

  def initialize(site)
    @site = site
    @cache = load_cache
    @added = {}
    @failed = {}
    @lookups = 0
    @failures = 0
    @last_request = nil
  end

  def enabled?
    ENV["PLACES_GEOCODE"].to_s != "0"
  end

  # Everything already known, as a downcased city => country hash, for
  # places.rb to fold in underneath the curated data.
  def cached
    @cache.each_with_object({}) { |(city, country), out| out[city.to_s.downcase] = country.to_s }
  end

  # The country at these coordinates, or nil if we can't say. `city` is only
  # used as the cache key and for logging — the coordinates do the work.
  def country_for(city, lat, lng)
    return nil unless enabled?
    return nil if city.to_s.strip.empty? || lat.nil? || lng.nil?
    return nil if @failures >= MAX_FAILURES
    # A city that already failed this build stays failed. Without this the
    # retry is per *venue*, so one unreachable city with several venues burns
    # a lookup apiece and trips the breaker on what is really a single failure.
    return nil if @failed[city.to_s.downcase]

    if @lookups >= MAX_LOOKUPS
      Jekyll.logger.warn "Places:", "geocode cap (#{MAX_LOOKUPS}) reached — #{city} left unplaced this build"
      return nil
    end

    @lookups += 1
    country = request_country(lat, lng)
    if country.nil?
      @failed[city.to_s.downcase] = true
      @failures += 1
      if @failures >= MAX_FAILURES
        Jekyll.logger.warn "Places:", "geocoding unavailable — giving up for this build; " \
          "unplaced cities group under \"Elsewhere\" (set PLACES_GEOCODE=0 to skip this entirely)"
      end
      return nil
    end

    @failures = 0
    @added[city] = country
    @cache[city] = country
    Jekyll.logger.info "Places:", "geocoded #{city} → #{country}"
    country
  end

  # Persist anything new. Best-effort: on a read-only or ephemeral filesystem
  # (a CI runner) the lookup still worked for this build, it just won't be
  # remembered — which is why the cache is meant to be committed from a local
  # build.
  def flush!
    return if @added.empty?
    path = @site.in_source_dir(CACHE_PATH)
    body = +"# Generated by _plugins/places_geocode.rb — country by coordinates,\n" \
            "# for destinations neither _data/places_geo.yml nor the vault names.\n" \
            "# Safe to edit or delete (it just gets looked up again), and safe to\n" \
            "# promote: move a line into places_geo.yml's `countries:` to make it\n" \
            "# curated. Commit this so the lookups don't repeat.\n"
    @cache.keys.sort_by(&:downcase).each { |city| body << "#{YAML.dump(city => @cache[city]).sub(/\A---\n/, '')}" }
    # Write-then-rename: a build killed mid-write leaves the old cache intact
    # rather than a truncated file to be ignored (and re-fetched) next time.
    tmp = "#{path}.tmp"
    File.write(tmp, body)
    File.rename(tmp, path)
    Jekyll.logger.info "Places:", "wrote #{@added.size} new entr#{@added.size == 1 ? 'y' : 'ies'} to #{CACHE_PATH}"
  rescue SystemCallError, IOError => e
    Jekyll.logger.warn "Places:", "couldn't write #{CACHE_PATH} (#{e.message}) — lookups will repeat next build"
  end

  private

  def load_cache
    path = @site.in_source_dir(CACHE_PATH)
    return {} unless File.exist?(path)
    data = YAML.safe_load(File.read(path)) || {}
    data.is_a?(Hash) ? data : {}
  rescue StandardError => e
    Jekyll.logger.warn "Places:", "ignoring unreadable #{CACHE_PATH} (#{e.message})"
    {}
  end

  # Nominatim's usage policy: one request per second, and a User-Agent that
  # identifies the caller. `accept-language=en` so we get "Italy" rather than
  # whatever the local exonym is — the tree keys on the name.
  def request_country(lat, lng)
    throttle
    uri = URI(endpoint)
    uri.query = URI.encode_www_form(
      lat: lat, lon: lng, format: "json", zoom: 3,
      addressdetails: 1, "accept-language" => "en"
    )

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == "https"
    http.open_timeout = TIMEOUT
    http.read_timeout = TIMEOUT

    req = Net::HTTP::Get.new(uri)
    req["User-Agent"] = USER_AGENT
    res = http.request(req)

    unless res.code == "200"
      Jekyll.logger.warn "Places:", "geocoder returned #{res.code} for #{lat}, #{lng}"
      return nil
    end

    country = JSON.parse(res.body).dig("address", "country")
    return country unless country.to_s.strip.empty?
    Jekyll.logger.warn "Places:", "geocoder gave no country for #{lat}, #{lng}"
    nil
  rescue StandardError => e
    Jekyll.logger.warn "Places:", "geocoding failed for #{lat}, #{lng}: #{e.message}"
    nil
  end

  def endpoint
    ep = ENV["PLACES_GEOCODE_ENDPOINT"].to_s
    ep.empty? ? DEFAULT_ENDPOINT : ep
  end

  def throttle
    if @last_request
      wait = THROTTLE - (Time.now - @last_request)
      sleep(wait) if wait.positive?
    end
    @last_request = Time.now
  end
end
